name: End-to-end tests
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cypress Run
        uses: cypress-io/github-action@1
        with:
          command: yarn cypress run
